diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'

urlpatterns = [

]

moviedb/urls.py
from django.urls import path
from . import views

app_name = 'moviedb'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('detail/<int:pk>', views.MovieDetail.as_view(), name='movie_detail'),
    path('list/', views.Movielist.as_view(), name='movie_list'),
]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daiaries/', include('diaries.urls')),
    path('moviedb/', include('moviedb.urls')),
]

diaries/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Category(models.Model):
    name = models.CharField('カテゴリ', max_length=255)

    def __str__(self):
        return self.name

class Diary(models.Model):
    category = models.ForeignKey(Category, verbose_name ='カテゴリ', on_delete=models.PROTECT)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return 'カテゴリ:{} 本文:{}'.format(self.category,self.text[:10])

moviedb/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    """"映画リスト"""
    disk = models.IntegerField(verbose_name="ディスク番号",blank=True, null=True)
    title = models.CharField(verbose_name="タイトル", max_length=100)
    overview = models.CharField(verbose_name="概説",max_length=100)
    explain = models.CharField(verbose_name="解説",max_length=800)
    viewed_at = models.DateField(verbose_name='視聴日', blank=True, null=True)
    recorded_at = models.DateField(verbose_name='録画日',blank=True, null=True)
    media = models.CharField(verbose_name='メディア', max_length=50, blank=True, null=True)
    genre = models.CharField(verbose_name='ジャンル', max_length=50, blank=True)
    def __str__(self):
        return self.title

diaries/views.py
from django.shortcuts import render

# Create your views here.

moviedb/views.py
from django.shortcuts import render
from django.views import generic
from .models import Movie
from django.db.models import Q
from moviedb.forms import SearchForm
from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
    model = Movie
    template_name = "moviedb/index.html"
    paginate_by = 10
    f = SearchForm()

    def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            object_list = Movie.objects.filter(
                Q(title__icontains=q_word) | Q(explain__icontains=q_word))
        else:
            object_list = Movie.objects.all()
        RNum = object_list.count
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['Qstring'] = self.request.GET.get('query')
        context['qword'] = self.request.GET.urlencode()
        context['Num'] = self.object_list.count()
        return context

class MovieDetail(generic.DetailView):
    model = Movie

class Movielist(generic.ListView):
    model = Movie
    template_name = 'moviedb/movie_list.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    def get_queryset(self):
        # original qs
        qs = super().get_queryset()
        # filter by a variable captured from url, for example
        #return qs.filter(explain__startswith=self.kwargs['name'])
        return qs.filter(explain__icontains='アカデミー')

moviedb/templates/moviedb/base.html
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="Viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <style></style>  　　
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input name ="query" value = "{{ request.GET.query }}" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container-fluid">
    {% block content %}{% endblock %}
<div class="container">
</body>
</html>

moviedb/templates/moviedb/index.html
{% extends 'moviedb/base.html' %}

{% block content %}
<div class="container">
  <h1>ビデオリスト</h1>
  <hr>
  {% include "moviedb/movie_list.html" %}
  {% include "moviedb/pagination.html" %}
</div>
{% endblock %}

moviedb/templates/moviedb/movie_detail.html
{% extends 'moviedb/base.html' %}

{% block content %}
    <article>
        <h1>{{ movie.title }}</h1>
        <p>Disk No.{{ movie.disk}}</p>
        <p>{{ movie.overview }} - 放送日：{{ movie.recorded_at }}</p>
        <p>{{ movie.explain | linebreaks }}</p>
    </article>
{% endblock %}

moviedb/templates/moviedb/movie_list.html
{% block content %}
<div class="row">
    <div class="col">
        <table class="table table-striped">
          <thead class="thead-dark"><tr><th>disk</th><th>title</th><th>overview</th></tr></thead>
            <tbody>
                {% for movie in movie_list %}
                <tr><th>{{ movie.disk}}</th><td><a href="{% url 'moviedb:movie_detail' movie.pk %}">{{ movie.title }}</a></td><td>{{ movie.overview }}</td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

moviedb/templates/moviedb/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation example">

    <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1{% if request.GET.query %}&q={{ request.GET.query }}{% endif %}">
                    <span aria-hidden="true">first</span>
                </a>
            </li>

            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.query %}&q={{ request.GET.query }}{% endif %}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:3 and num >= page_obj.number|add:-3 %}

                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}{% if request.GET.query %}&q={{ request.GET.query }}{% endif %}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}

            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.query %}&q={{ request.GET.query }}{% endif %}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>

      　　　 <li class="page-item">
                <a class="page-link" href="?page={{page_obj.paginator.num_pages}}{% if request.GET.query %}&q={{ request.GET.query }}{% endif %}">
                    <span aria-hidden="true">last</span>
                </a>
            </li>
        {% endif %}
    </ul>

</nav>
{% endif %}